export const ACTUALIZAR_COLECTIVOS = "ACTUALIZAR_COLECTIVOS";
export const ELEGIR_LINEA_DE_COLECTIVO = "ELEGIR_LINEA_DE_COLECTIVO";
export const INICIAR_TIMER = 'INICIAR_TIMER';
export const DETENER_TIMER = 'DETENER_TIMER';
export const COLECTIVO_SELECCIONADO = 'COLECTIVO_SELECCIONADO';
